services:
  - type: web
    name: face-recognition-app
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 8
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 
